// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.EmployeeMvp
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EmployeeMVP")]
    [NUnit.Framework.IgnoreAttribute("Ignored feature")]
    public partial class EmployeeMVPFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EmployeeMvp.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EmployeeMVP", "\tScenario 1:  VD-24 - Peer Kudos Dashboard - Valid Login Credentials\r\n\tEnter vali" +
                    "d username/password combo, verify Peer Kudos Dashboard page\r\n\r\n\tScenario 2: VD-2" +
                    "4 - Peer Kudos Dashboard - Invalid Login Credentials\r\n\tEnter invalid username/pa" +
                    "ssword, verify error message and prompt to reenter credentials\r\n\r\n\tScenario 3: V" +
                    "D-25 - Peer Kudos Dashboard - Employee of the Month\r\n\tVerify First & Last Name o" +
                    "f employee with the Maximum Stars during the last month\r\n\tView count of stars di" +
                    "splayed\r\n\tTie-Out ??? - view runner ups & count of stars for each\r\n\r\n\tScenario 4" +
                    ": VD-26 - Peer Kudos Dashboard - Current Month Top 5 Employees Ranks\r\n\tTop 5 Ran" +
                    "ked Employees \r\n\tIn Descending order of count of stars for current month\r\n\r\n\tSce" +
                    "nario 5: VD-28 - Peer Kudos Dashboard - Search Employee\r\n\tSearch an employee usi" +
                    "ng substring of First or Last Name (to select them for a kudo)\r\n\tResults are sor" +
                    "ted by First Name\r\n\r\n\tScenario 6: VD-29 - Peer Kudos Dashboard - Assign stars to" +
                    " employees in Top 5\r\n\tClick next to name of \"top-5\" employee and enter stars (1," +
                    " 2, or 3 only)\r\n\r\n\tScenario 7: VD-29 - Peer Kudos Dashboard - Search Employee an" +
                    "d Assign stars\r\n\tSearch for an employee\r\n\tClick next to name of employee in sear" +
                    "ch results and enter stars (1, 2, or 3 only)\r\n\t\r\n\tScenario 8: VD-27 - Peer Kudos" +
                    " Dashboard - My Current Month Ranking\r\n\tNext to my name, view count of stars I c" +
                    "ollected for current month\r\n\tNext to my name, view count of stars I have given o" +
                    "ut for current month\r\n\tNext to my name, view count of stars I have remaining for" +
                    " current month\r\n\tView my Star Ranking Order \r\n\r\n\tScenario 9: VD-32 - Admin - Log" +
                    "in with Valid Credentials\r\n\tAdmin users with valid credentials (marked as Admin " +
                    "users - where ??) are directed to Peer Kudos Admin Employee Directory page\r\n\r\n\tS" +
                    "cenario 10: VD-32 - Admin - Login with Invalid Credentials\r\n\tAdmin users with in" +
                    "valid credentials (or not marked as Admin users - where ??) -- error message is " +
                    "displayed\r\n\r\n\tScenario 11: VD-33 - Admin - View Employee Directory\r\n\tAdmin can v" +
                    "iew list of all employees sorted by name\r\n\r\n\tScenario 12: VD-35 - Admin - Update" +
                    " Employee Info\r\n\tAdmin user can select any employee and update all info\r\n\tAdmin " +
                    "user can save and verify updates\r\n\tUpdates must follow uniqueness for Username, " +
                    "First & Last Name\r\n\r\n\tScenario 13: VD-34 - Admin - Add Employee\r\n\tAdmin user can" +
                    " create a new employee - First, Last Name, Username, Password, Admin (yes/no)\r\n\r" +
                    "\n\tScenario 14: VD-34 - Admin - Add Employee (verify duplicate errors)\r\n\tDuplicat" +
                    "e First + Last Name combination displays errors\r\n\tUpdating to remove duplicates " +
                    "allows to save new employee\r\n\tDuplicate Username shoudl display errors\r\n\tUpdatin" +
                    "g to remove duplicate username allows to save\r\n\r\n\tScenario 15: VD-36 - Admin - D" +
                    "elete Employees\r\n\tAdmin can delete an employee and accept confirmation dialog.\r\n" +
                    "\tSearch for the deleted employee should return no records\r\n\r\n\tScenario 16: VD-38" +
                    " - Reports: Report by Month\r\n\tAdmin selects \'Report by Month\' - select Month/Yea" +
                    "r\r\n\tList of employees displayed with stars for that month in Descending Order fo" +
                    "llowed by First/Last Name Asending Order\r\n\r\n\tScenario 17: VD-38 - Reports: Repor" +
                    "t by Employee\r\n\tAdmin selects \'Report by Employee\' - enter partial employee Firs" +
                    "t/Last Name\r\n\tSelect from result employee list\r\n\tResult displays count of stars " +
                    "collected received each Month\r\n\r\n\tScenario 18: VD-38 - Max 10 stars can be given" +
                    " out for current month\r\n\tVerify max 10 stars can be given out for current month\r" +
                    "\n\tExceeding limit prompts error message\r\n\r\n\tScenario 19: Peer Kudos Dashboard - " +
                    "Logout of the application", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-VD-24 - Peer Kudos Dashboard - Valid Login Credentials")]
        public virtual void _01_VD_24_PeerKudosDashboard_ValidLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-VD-24 - Peer Kudos Dashboard - Valid Login Credentials", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line 79
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.Then("the page contains the text \"Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.And("the page contains the text \"Kudos Received\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-VD-24 - Peer Kudos Dashboard - Invalid Login Credentials")]
        public virtual void _02_VD_24_PeerKudosDashboard_InvalidLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-VD-24 - Peer Kudos Dashboard - Invalid Login Credentials", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line 87
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"invalidUs" +
                    "erid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"invalidPa" +
                    "ssword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.Then("the page contains the text \"Invalid Username or password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Log back into the App")]
        public virtual void _03_LogBackIntoTheApp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Log back into the App", ((string[])(null)));
#line 93
this.ScenarioSetup(scenarioInfo);
#line 94
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 95
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 96
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.Then("the page contains the text \"Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Verify Employee Table")]
        public virtual void _04_VerifyEmployeeTable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Verify Employee Table", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line 101
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 102
 testRunner.When("I access the table using element id \"Give-Kudos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.And("I set the text box using name attribute \"q\" with the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.Then("table row number \"1\" column number \"1\" contains the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.And("table row number \"1\" column number \"2\" contains the value \"Brailovsky\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("table row number \"1\" column number \"3\" contains the value \"7\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-VD-25 - Peer Kudos Dashboard - Employee of the Previous Month")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _03_VD_25_PeerKudosDashboard_EmployeeOfThePreviousMonth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-VD-25 - Peer Kudos Dashboard - Employee of the Previous Month", new string[] {
                        "ignore"});
#line 110
this.ScenarioSetup(scenarioInfo);
#line 114
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 115
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 116
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.When("I access the table using element id \"top_employees_of_last_month\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.Then("the count of rows in the table is \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-VD-26 - Peer Kudos Dashboard - Current Month Top 5 Employees Ranks")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _04_VD_26_PeerKudosDashboard_CurrentMonthTop5EmployeesRanks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-VD-26 - Peer Kudos Dashboard - Current Month Top 5 Employees Ranks", new string[] {
                        "ignore"});
#line 127
this.ScenarioSetup(scenarioInfo);
#line 129
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 130
 testRunner.When("I access the table using element id \"top_5_employees_of_the_current_month\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
 testRunner.Then("the count of rows in the table is \"5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05-VD-28 - Peer Kudos Dashboard - Search Employee")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _05_VD_28_PeerKudosDashboard_SearchEmployee()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05-VD-28 - Peer Kudos Dashboard - Search Employee", new string[] {
                        "ignore"});
#line 136
this.ScenarioSetup(scenarioInfo);
#line 138
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And("I set the text box using name attribute \"q\" with the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.And("I access the table using element id \"employee_table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.Then("table row number \"1\" column number \"1\" contains the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 146
 testRunner.And("table row number \"1\" column number \"2\" contains the value \"Brailovsky*", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
 testRunner.And("table row number \"1\" column number \"3\" contains the value \"4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-VD-29 - Peer Kudos Dashboard - Assign stars to employees in Top 5")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _06_VD_29_PeerKudosDashboard_AssignStarsToEmployeesInTop5()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-VD-29 - Peer Kudos Dashboard - Assign stars to employees in Top 5", new string[] {
                        "ignore"});
#line 152
this.ScenarioSetup(scenarioInfo);
#line 154
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 155
 testRunner.When("I save the data using element id \"top_1_of_5_employee\" into the variable \"current" +
                    "StarCount\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
 testRunner.And("I click on the button using element id \"3-star\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-VD-29 - Peer Kudos Dashboard - Assign stars to employees displayed in Search R" +
            "esults")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _07_VD_29_PeerKudosDashboard_AssignStarsToEmployeesDisplayedInSearchResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-VD-29 - Peer Kudos Dashboard - Assign stars to employees displayed in Search R" +
                    "esults", new string[] {
                        "ignore"});
#line 165
this.ScenarioSetup(scenarioInfo);
#line 168
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 169
 testRunner.When("I set the text box using element id \"search_employee\" with the value \"xyz\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 170
 testRunner.And("I access the table using element id \"employee_table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.And("I save the data from table row number \"1\" column number \"3\" into the variable \"cu" +
                    "rrentStarCount\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.And("I click on the button using element id \"2-star\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08-VD-27 - Peer Kudos Dashboard - My Current Month Ranking")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _08_VD_27_PeerKudosDashboard_MyCurrentMonthRanking()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08-VD-27 - Peer Kudos Dashboard - My Current Month Ranking", new string[] {
                        "ignore"});
#line 181
this.ScenarioSetup(scenarioInfo);
#line 186
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 189
 testRunner.Then("the element using element Id \"my_star_collection_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 190
 testRunner.Then("the element using element Id \"my_star_given_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 191
 testRunner.Then("the element using element Id \"my_star_remaining_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 192
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-VD-32 - Admin - Login")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _09_VD_32_Admin_Login()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-VD-32 - Admin - Login", new string[] {
                        "ignore"});
#line 195
this.ScenarioSetup(scenarioInfo);
#line 198
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com/users/sign_in\" tit" +
                    "led \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 199
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"admin@exa" +
                    "mple.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 200
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"supers" +
                    "ecret\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 201
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
 testRunner.Then("the page title is \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 203
 testRunner.And("the page contains the text \"Catalog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-VD-32 - Admin - Login with Valid Credentials")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _10_VD_32_Admin_LoginWithValidCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-VD-32 - Admin - Login with Valid Credentials", new string[] {
                        "ignore"});
#line 206
this.ScenarioSetup(scenarioInfo);
#line 207
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 208
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"invalidUs" +
                    "erId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 209
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"invali" +
                    "dPassword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 210
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11-VD-33 - Admin - Login with Invalid Credentials")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _11_VD_33_Admin_LoginWithInvalidCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11-VD-33 - Admin - Login with Invalid Credentials", new string[] {
                        "ignore"});
#line 214
this.ScenarioSetup(scenarioInfo);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19-Peer Kudos Dashboard - Logout of the application")]
        public virtual void _19_PeerKudosDashboard_LogoutOfTheApplication()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19-Peer Kudos Dashboard - Logout of the application", ((string[])(null)));
#line 217
this.ScenarioSetup(scenarioInfo);
#line 218
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 219
 testRunner.When("I click on the link containing the text \"Sign out\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 220
 testRunner.Then("the page contains the text \"You need to sign in or sign up before continuing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 221
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
