// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.EmployeeMvp
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Galaxy App")]
    public partial class GalaxyAppFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Galaxy.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Galaxy App", "\t01-Invalid Non-Admin Login Credentials\r\n\t\r\n\t02-Invalid Admin Login Credentials\r\n" +
                    "\r\n\t03-Valid Non-Admin Login Credentials\r\n\r\n\t04-Logout as a Regular User\r\n\r\n\t05-V" +
                    "alid Admin Login Credentials\r\n\r\n\t06-Give a point to another user\r\n\r\n\t07-Add New " +
                    "User\r\n\r\n\r\n\r\n\tScenario 1:  Peer Kudos Dashboard - Valid Login Credentials\r\n\tEnter" +
                    " valid username/password combo, verify Peer Kudos Dashboard page\r\n\r\n\tScenario 2:" +
                    " Peer Kudos Dashboard - Invalid Login Credentials\r\n\tEnter invalid username/passw" +
                    "ord, verify error message and prompt to reenter credentials\r\n\r\n\tScenario 3: Peer" +
                    " Kudos Dashboard - Employee of the Month\r\n\tVerify First & Last Name of employee " +
                    "with the Maximum Stars during the last month\r\n\tView count of stars displayed\r\n\tT" +
                    "ie-Out ??? - view runner ups & count of stars for each\r\n\r\n\tScenario 4: Peer Kudo" +
                    "s Dashboard - Current Month Top 5 Employees Ranks\r\n\tTop 5 Ranked Employees \r\n\tIn" +
                    " Descending order of count of stars for current month\r\n\r\n\tScenario 5: Peer Kudos" +
                    " Dashboard - Search Employee\r\n\tSearch an employee using substring of First or La" +
                    "st Name (to select them for a kudo)\r\n\tResults are sorted by First Name\r\n\r\n\tScena" +
                    "rio 6: Peer Kudos Dashboard - Assign stars to employees in Top 5\r\n\tClick next to" +
                    " name of \"top-5\" employee and enter stars (1, 2, or 3 only)\r\n\r\n\tScenario 7: Peer" +
                    " Kudos Dashboard - Search Employee and Assign stars\r\n\tSearch for an employee\r\n\tC" +
                    "lick next to name of employee in search results and enter stars (1, 2, or 3 only" +
                    ")\r\n\t\r\n\tScenario 8: Peer Kudos Dashboard - My Current Month Ranking\r\n\tNext to my " +
                    "name, view count of stars I collected for current month\r\n\tNext to my name, view " +
                    "count of stars I have given out for current month\r\n\tNext to my name, view count " +
                    "of stars I have remaining for current month\r\n\tView my Star Ranking Order \r\n\r\n\tSc" +
                    "enario 9: Admin - Login with Valid Credentials\r\n\tAdmin users with valid credenti" +
                    "als (marked as Admin users - where ??) are directed to Peer Kudos Admin Employee" +
                    " Directory page\r\n\r\n\tScenario 10: Admin - Login with Invalid Credentials\r\n\tAdmin " +
                    "users with invalid credentials (or not marked as Admin users - where ??) -- erro" +
                    "r message is displayed\r\n\r\n\tScenario 11: Admin - View Employee Directory\r\n\tAdmin " +
                    "can view list of all employees sorted by name\r\n\r\n\tScenario 12: Admin - Update Em" +
                    "ployee Info\r\n\tAdmin user can select any employee and update all info\r\n\tAdmin use" +
                    "r can save and verify updates\r\n\tUpdates must follow uniqueness for Username, Fir" +
                    "st & Last Name\r\n\r\n\tScenario 13: Admin - Add Employee\r\n\tAdmin user can create a n" +
                    "ew employee - First, Last Name, Username, Password, Admin (yes/no)\r\n\r\n\tScenario " +
                    "14: Admin - Add Employee (verify duplicate errors)\r\n\tDuplicate First + Last Name" +
                    " combination displays errors\r\n\tUpdating to remove duplicates allows to save new " +
                    "employee\r\n\tDuplicate Username shoudl display errors\r\n\tUpdating to remove duplica" +
                    "te username allows to save\r\n\r\n\tScenario 15: Admin - Delete Employees\r\n\tAdmin can" +
                    " delete an employee and accept confirmation dialog.\r\n\tSearch for the deleted emp" +
                    "loyee should return no records\r\n\r\n\tScenario 16: Reports: Report by Month\r\n\tAdmin" +
                    " selects \'Report by Month\' - select Month/Year\r\n\tList of employees displayed wit" +
                    "h stars for that month in Descending Order followed by First/Last Name Asending " +
                    "Order\r\n\r\n\tScenario 17: Reports: Report by Employee\r\n\tAdmin selects \'Report by Em" +
                    "ployee\' - enter partial employee First/Last Name\r\n\tSelect from result employee l" +
                    "ist\r\n\tResult displays count of stars collected received each Month\r\n\r\n\tScenario " +
                    "18: Max 10 stars can be given out for current month\r\n\tVerify max 10 stars can be" +
                    " given out for current month\r\n\tExceeding limit prompts error message\r\n\r\n\tScenari" +
                    "o 19: Peer Kudos Dashboard - Logout of the application", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-Invalid Non-Admin Login Credentials")]
        public virtual void _01_InvalidNon_AdminLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-Invalid Non-Admin Login Credentials", ((string[])(null)));
#line 92
this.ScenarioSetup(scenarioInfo);
#line 93
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 94
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"chris@abc.co" +
                    "m\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 95
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"invalidPa" +
                    "ssword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.Then("the page contains the text \"Invalid Email or password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-Invalid Admin Login Credentials")]
        public virtual void _02_InvalidAdminLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-Invalid Admin Login Credentials", ((string[])(null)));
#line 99
this.ScenarioSetup(scenarioInfo);
#line 100
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 101
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"alex@abc.com" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"invalidPa" +
                    "ssword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.Then("the page contains the text \"Invalid Email or password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Valid Admin Login Credentials")]
        public virtual void _03_ValidAdminLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Valid Admin Login Credentials", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"alex@abc.com" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.Then("the page contains the text \"Admin Dashboard\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Logout as an Admin User")]
        public virtual void _04_LogoutAsAnAdminUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Logout as an Admin User", ((string[])(null)));
#line 113
this.ScenarioSetup(scenarioInfo);
#line 114
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 115
 testRunner.When("I click on the link containing the text \"Sign out\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 116
 testRunner.Then("the page contains the text \"You need to sign in or sign up before continuing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05-Valid Non-Admin Login Credentials")]
        public virtual void _05_ValidNon_AdminLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05-Valid Non-Admin Login Credentials", ((string[])(null)));
#line 118
this.ScenarioSetup(scenarioInfo);
#line 119
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"chris@abc.co" +
                    "m\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"letmein\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 122
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.Then("the page contains the text \"Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-User Help Text on Page")]
        public virtual void _06_UserHelpTextOnPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-User Help Text on Page", ((string[])(null)));
#line 125
this.ScenarioSetup(scenarioInfo);
#line 126
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 127
 testRunner.Then("the page contains the text \"You can give someone up to 1 Kudo per day\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 128
 testRunner.And("the page contains the text \"Click on the star to the right of your colleagues nam" +
                    "e in the table to give them a Kudo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-User Help Link")]
        public virtual void _07_UserHelpLink()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-User Help Link", ((string[])(null)));
#line 130
this.ScenarioSetup(scenarioInfo);
#line 131
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 132
 testRunner.When("I click on the link containing the text \"Help\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 133
 testRunner.Then("the page contains the text \"This is user help text\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08-Admin Search")]
        public virtual void _08_AdminSearch()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08-Admin Search", ((string[])(null)));
#line 136
this.ScenarioSetup(scenarioInfo);
#line 137
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 138
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"alex@abc.com" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 139
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("I set the text box using element id \"employee-search\" with the value \"bella\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"employe" +
                    "e-table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.Then("table row number \"2\" column number \"1\" contains the value \"bella.trenkova@variq.c" +
                    "om\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-Deactivate User")]
        public virtual void _09_DeactivateUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-Deactivate User", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line 147
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 148
 testRunner.When("I click on the link containing the text \"Edit\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 149
 testRunner.And("I set the checkbox with element id \"employee_is_active\" to \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
 testRunner.And("I click on the submit button labeled \"Save changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-FAQ")]
        public virtual void _10_FAQ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-FAQ", ((string[])(null)));
#line 152
this.ScenarioSetup(scenarioInfo);
#line 153
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 154
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"alex@abc.com" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 155
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.When("I click on the link containing the text \"FAQ\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
 testRunner.Then("the page contains the text \"This is your FAQ text\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Give a point to another user")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _16_GiveAPointToAnotherUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Give a point to another user", new string[] {
                        "ignore"});
#line 162
this.ScenarioSetup(scenarioInfo);
#line 163
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 165
 testRunner.When("I upload file \"UploadFiles\\test.gif\" using element id \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 168
 testRunner.Then("the page title is \"Give a Point\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Add New User")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _17_AddNewUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Add New User", new string[] {
                        "ignore"});
#line 171
this.ScenarioSetup(scenarioInfo);
#line 172
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19-Disable User Account")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _19_DisableUserAccount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19-Disable User Account", new string[] {
                        "ignore"});
#line 177
this.ScenarioSetup(scenarioInfo);
#line 178
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-Enable User Account")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _10_EnableUserAccount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-Enable User Account", new string[] {
                        "ignore"});
#line 182
this.ScenarioSetup(scenarioInfo);
#line 183
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Non-Admin-Validate Profile fields")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.TestCaseAttribute("Name", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kudos Received", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kudos to Give", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Current Ranking", new string[0])]
        public virtual void _16_Non_Admin_ValidateProfileFields(string textOnPage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ignore"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Non-Admin-Validate Profile fields", @__tags);
#line 191
this.ScenarioSetup(scenarioInfo);
#line 192
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 193
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16-Non-Admin-Search Employee Table with Full First Name")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _16_Non_Admin_SearchEmployeeTableWithFullFirstName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16-Non-Admin-Search Employee Table with Full First Name", new string[] {
                        "ignore"});
#line 203
this.ScenarioSetup(scenarioInfo);
#line 204
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 205
 testRunner.When("I set the text box using name attribute \"q\" with the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 206
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"Give-Ku" +
                    "dos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 208
 testRunner.Then("table row number \"2\" column number \"1\" contains the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 209
 testRunner.And("table row number \"2\" column number \"2\" contains the value \"Brailovsky\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Non-Admin-Search Employee Table with Partial Name")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _17_Non_Admin_SearchEmployeeTableWithPartialName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Non-Admin-Search Employee Table with Partial Name", new string[] {
                        "ignore"});
#line 212
this.ScenarioSetup(scenarioInfo);
#line 213
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 214
 testRunner.When("I set the text box using name attribute \"q\" with the value \"a\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 215
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"Give-Ku" +
                    "dos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 217
 testRunner.Then("the count of rows in the table is greater than \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18-Non-Admin-Peer Kudos Dashboard - Current Month Top 5 Employees Ranks")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _18_Non_Admin_PeerKudosDashboard_CurrentMonthTop5EmployeesRanks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18-Non-Admin-Peer Kudos Dashboard - Current Month Top 5 Employees Ranks", new string[] {
                        "ignore"});
#line 220
this.ScenarioSetup(scenarioInfo);
#line 222
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 223
 testRunner.When("I access the table using element id \"leaderboard-table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 224
 testRunner.Then("the count of rows in the table is greater than \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 227
 testRunner.And("table row number \"2\" column number \"1\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 228
 testRunner.And("table row number \"3\" column number \"1\" contains the value \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17-Non-Admin-Assign stars to employees displayed in Search Results")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _17_Non_Admin_AssignStarsToEmployeesDisplayedInSearchResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17-Non-Admin-Assign stars to employees displayed in Search Results", new string[] {
                        "ignore"});
#line 231
this.ScenarioSetup(scenarioInfo);
#line 232
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 233
 testRunner.When("I set the text box using name attribute \"q\" with the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 234
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.And("I search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 236
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"Give-Ku" +
                    "dos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 237
 testRunner.And("I save the data from table row number \"2\" column number \"3\" into the variable \"in" +
                    "itialKudos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
 testRunner.And("I click on the element using tag \"span\" attribute type \"data-kudos-amount\" attrib" +
                    "ute value \"1\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
 testRunner.And("I set the text box using element id \"kudo_transaction\" with the value \"Awesome!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-Admin-Manage Employees")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _10_Admin_ManageEmployees()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-Admin-Manage Employees", new string[] {
                        "ignore"});
#line 245
this.ScenarioSetup(scenarioInfo);
#line 246
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 247
 testRunner.When("I click on the link containing the text \"Manage Employees\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 248
 testRunner.Then("the page contains the text \"Admin Dashboard\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11-Admin-Add New Employee")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _11_Admin_AddNewEmployee()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11-Admin-Add New Employee", new string[] {
                        "ignore"});
#line 251
this.ScenarioSetup(scenarioInfo);
#line 252
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 253
 testRunner.When("I click on the link containing the text \"Add New Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 254
 testRunner.And("the page contains the text \"Add New Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
 testRunner.And("I save a random string with \"8\" characters into the variable \"username\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.And("I set the text box using element id \"employee_email\" with the value stored in the" +
                    " variable \"username\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 261
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"Autotest1" +
                    "23!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 262
 testRunner.And("I set the text box using element id \"employee_password_confirmation\" with the val" +
                    "ue \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("I append the following strings \"[username],@,test.com\" and save the result into t" +
                    "he variable \"emailAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 266
 testRunner.And("I set the text box using element id \"employee_email\" with the value stored in the" +
                    " variable \"emailAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 268
 testRunner.And("I set the text box using element id \"employee_first_name\" with the value \"TestUse" +
                    "r-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 269
 testRunner.And("I set the text box using element id \"employee_last_name\" with the value \"User-LN\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 270
 testRunner.And("I set the checkbox with element id \"employee_is_admin\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 271
 testRunner.And("I click on the submit button labeled \"Save changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 272
 testRunner.Then("the page contains the text \"Employee was successfully created\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("72-Peer Kudos Dashboard - Employee of the Previous Month")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _72_PeerKudosDashboard_EmployeeOfThePreviousMonth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("72-Peer Kudos Dashboard - Employee of the Previous Month", new string[] {
                        "ignore"});
#line 276
this.ScenarioSetup(scenarioInfo);
#line 278
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 279
 testRunner.Then("the page using element id \"Panel-Last Month\'s Winner\" and attribute type \"div\" co" +
                    "ntains the text \"Alex Duan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("73-Peer Kudos Dashboard - Assign stars to employees in Top 5")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _73_PeerKudosDashboard_AssignStarsToEmployeesInTop5()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("73-Peer Kudos Dashboard - Assign stars to employees in Top 5", new string[] {
                        "ignore"});
#line 283
this.ScenarioSetup(scenarioInfo);
#line 285
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 286
 testRunner.When("I save the data using element id \"top_1_of_5_employee\" into the variable \"current" +
                    "StarCount\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 287
 testRunner.And("I click on the button using element id \"3-star\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("75-Peer Kudos Dashboard - My Current Month Ranking")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _75_PeerKudosDashboard_MyCurrentMonthRanking()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("75-Peer Kudos Dashboard - My Current Month Ranking", new string[] {
                        "ignore"});
#line 297
this.ScenarioSetup(scenarioInfo);
#line 302
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 305
 testRunner.Then("the element using element Id \"Panel-Last Month\'s Winner\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 306
 testRunner.Then("the element using element Id \"my_star_given_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 307
 testRunner.Then("the element using element Id \"my_star_remaining_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 308
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("76-Admin - Login")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _76_Admin_Login()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76-Admin - Login", new string[] {
                        "ignore"});
#line 311
this.ScenarioSetup(scenarioInfo);
#line 314
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"ShoppingD" +
                    "emo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 315
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"admin@exa" +
                    "mple.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 316
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"supers" +
                    "ecret\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 317
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 318
 testRunner.Then("the page title is \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 319
 testRunner.And("the page contains the text \"Catalog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("77-Peer Kudos Dashboard - Valid Admin Login Credentials")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _77_PeerKudosDashboard_ValidAdminLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("77-Peer Kudos Dashboard - Valid Admin Login Credentials", new string[] {
                        "ignore"});
#line 322
this.ScenarioSetup(scenarioInfo);
#line 323
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 324
 testRunner.When("I set the text box using element id \"employee_email\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 325
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 326
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 327
 testRunner.Then("the page contains the text \"Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 328
 testRunner.And("the page contains the text \"Kudos Received\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("78-Admin - Login with Valid Credentials")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _78_Admin_LoginWithValidCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("78-Admin - Login with Valid Credentials", new string[] {
                        "ignore"});
#line 331
this.ScenarioSetup(scenarioInfo);
#line 332
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 333
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"invalidUs" +
                    "erId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 334
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"invali" +
                    "dPassword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 335
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
