// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features.EmployeeMvp
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NewEmployeeMVP")]
    public partial class NewEmployeeMVPFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NewEmployeeMvp.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NewEmployeeMVP", "\tScenario 1:  VD-24 - Peer Kudos Dashboard - Valid Login Credentials\r\n\tEnter vali" +
                    "d username/password combo, verify Peer Kudos Dashboard page\r\n\r\n\tScenario 2: VD-2" +
                    "4 - Peer Kudos Dashboard - Invalid Login Credentials\r\n\tEnter invalid username/pa" +
                    "ssword, verify error message and prompt to reenter credentials\r\n\r\n\tScenario 3: V" +
                    "D-25 - Peer Kudos Dashboard - Employee of the Month\r\n\tVerify First & Last Name o" +
                    "f employee with the Maximum Stars during the last month\r\n\tView count of stars di" +
                    "splayed\r\n\tTie-Out ??? - view runner ups & count of stars for each\r\n\r\n\tScenario 4" +
                    ": VD-26 - Peer Kudos Dashboard - Current Month Top 5 Employees Ranks\r\n\tTop 5 Ran" +
                    "ked Employees \r\n\tIn Descending order of count of stars for current month\r\n\r\n\tSce" +
                    "nario 5: VD-28 - Peer Kudos Dashboard - Search Employee\r\n\tSearch an employee usi" +
                    "ng substring of First or Last Name (to select them for a kudo)\r\n\tResults are sor" +
                    "ted by First Name\r\n\r\n\tScenario 6: VD-29 - Peer Kudos Dashboard - Assign stars to" +
                    " employees in Top 5\r\n\tClick next to name of \"top-5\" employee and enter stars (1," +
                    " 2, or 3 only)\r\n\r\n\tScenario 7: VD-29 - Peer Kudos Dashboard - Search Employee an" +
                    "d Assign stars\r\n\tSearch for an employee\r\n\tClick next to name of employee in sear" +
                    "ch results and enter stars (1, 2, or 3 only)\r\n\t\r\n\tScenario 8: VD-27 - Peer Kudos" +
                    " Dashboard - My Current Month Ranking\r\n\tNext to my name, view count of stars I c" +
                    "ollected for current month\r\n\tNext to my name, view count of stars I have given o" +
                    "ut for current month\r\n\tNext to my name, view count of stars I have remaining for" +
                    " current month\r\n\tView my Star Ranking Order \r\n\r\n\tScenario 9: VD-32 - Admin - Log" +
                    "in with Valid Credentials\r\n\tAdmin users with valid credentials (marked as Admin " +
                    "users - where ??) are directed to Peer Kudos Admin Employee Directory page\r\n\r\n\tS" +
                    "cenario 10: VD-32 - Admin - Login with Invalid Credentials\r\n\tAdmin users with in" +
                    "valid credentials (or not marked as Admin users - where ??) -- error message is " +
                    "displayed\r\n\r\n\tScenario 11: VD-33 - Admin - View Employee Directory\r\n\tAdmin can v" +
                    "iew list of all employees sorted by name\r\n\r\n\tScenario 12: VD-35 - Admin - Update" +
                    " Employee Info\r\n\tAdmin user can select any employee and update all info\r\n\tAdmin " +
                    "user can save and verify updates\r\n\tUpdates must follow uniqueness for Username, " +
                    "First & Last Name\r\n\r\n\tScenario 13: VD-34 - Admin - Add Employee\r\n\tAdmin user can" +
                    " create a new employee - First, Last Name, Username, Password, Admin (yes/no)\r\n\r" +
                    "\n\tScenario 14: VD-34 - Admin - Add Employee (verify duplicate errors)\r\n\tDuplicat" +
                    "e First + Last Name combination displays errors\r\n\tUpdating to remove duplicates " +
                    "allows to save new employee\r\n\tDuplicate Username shoudl display errors\r\n\tUpdatin" +
                    "g to remove duplicate username allows to save\r\n\r\n\tScenario 15: VD-36 - Admin - D" +
                    "elete Employees\r\n\tAdmin can delete an employee and accept confirmation dialog.\r\n" +
                    "\tSearch for the deleted employee should return no records\r\n\r\n\tScenario 16: VD-38" +
                    " - Reports: Report by Month\r\n\tAdmin selects \'Report by Month\' - select Month/Yea" +
                    "r\r\n\tList of employees displayed with stars for that month in Descending Order fo" +
                    "llowed by First/Last Name Asending Order\r\n\r\n\tScenario 17: VD-38 - Reports: Repor" +
                    "t by Employee\r\n\tAdmin selects \'Report by Employee\' - enter partial employee Firs" +
                    "t/Last Name\r\n\tSelect from result employee list\r\n\tResult displays count of stars " +
                    "collected received each Month\r\n\r\n\tScenario 18: VD-38 - Max 10 stars can be given" +
                    " out for current month\r\n\tVerify max 10 stars can be given out for current month\r" +
                    "\n\tExceeding limit prompts error message\r\n\r\n\tScenario 19: Peer Kudos Dashboard - " +
                    "Logout of the application", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01-Invalid Non-Admin Login Credentials (VD-24)")]
        public virtual void _01_InvalidNon_AdminLoginCredentialsVD_24()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01-Invalid Non-Admin Login Credentials (VD-24)", ((string[])(null)));
#line 76
this.ScenarioSetup(scenarioInfo);
#line 77
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 79
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"invalidUs" +
                    "erid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"invalidPa" +
                    "ssword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.Then("the page contains the text \"Invalid Username or password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02-Valid Non-Admin Login Credentials (VD-24)")]
        public virtual void _02_ValidNon_AdminLoginCredentialsVD_24()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02-Valid Non-Admin Login Credentials (VD-24)", ((string[])(null)));
#line 84
this.ScenarioSetup(scenarioInfo);
#line 85
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"maximumax" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.Then("the page contains the text \"Signed in successfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03-Admin-Validate Profile fields")]
        [NUnit.Framework.TestCaseAttribute("Name", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kudos Received", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Kudos to Give", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Current Ranking", new string[0])]
        public virtual void _03_Admin_ValidateProfileFields(string textOnPage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03-Admin-Validate Profile fields", exampleTags);
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
 testRunner.Then(string.Format("the page contains the text {0} from the following table", textOnPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04-Admin-Search Employee Table with Full First Name")]
        public virtual void _04_Admin_SearchEmployeeTableWithFullFirstName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04-Admin-Search Employee Table with Full First Name", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line 103
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
 testRunner.When("I set the text box using name attribute \"q\" with the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"Give-Ku" +
                    "dos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.Then("table row number \"2\" column number \"1\" contains the value \"Max\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
 testRunner.And("table row number \"2\" column number \"2\" contains the value \"Brailovsky\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05-Admin-Search Employee Table with Partial Name")]
        public virtual void _05_Admin_SearchEmployeeTableWithPartialName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05-Admin-Search Employee Table with Partial Name", ((string[])(null)));
#line 110
this.ScenarioSetup(scenarioInfo);
#line 111
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 112
 testRunner.When("I set the text box using name attribute \"q\" with the value \"a\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 113
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"Give-Ku" +
                    "dos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.Then("the count of rows in the table is greater than \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06-Admin-Peer Kudos Dashboard - Current Month Top 5 Employees Ranks (VD-26)")]
        public virtual void _06_Admin_PeerKudosDashboard_CurrentMonthTop5EmployeesRanksVD_26()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06-Admin-Peer Kudos Dashboard - Current Month Top 5 Employees Ranks (VD-26)", ((string[])(null)));
#line 117
this.ScenarioSetup(scenarioInfo);
#line 119
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
 testRunner.When("I access the table using element id \"leaderboard-table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.Then("the count of rows in the table is greater than \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 124
 testRunner.And("table row number \"2\" column number \"1\" contains the value \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("table row number \"3\" column number \"1\" contains the value \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07-Assign stars to employees displayed in Search Results (VD-29)")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _07_AssignStarsToEmployeesDisplayedInSearchResultsVD_29()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07-Assign stars to employees displayed in Search Results (VD-29)", new string[] {
                        "ignore"});
#line 128
this.ScenarioSetup(scenarioInfo);
#line 129
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 130
 testRunner.When("I set the text box using name attribute \"q\" with the value \"bella\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
 testRunner.And("I click on the submit button containing the text \"Search!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.And("I access the table using tag \"table\" attribute type \"id\" attribute value \"Give-Ku" +
                    "dos-Table\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("I save the data from table row number \"2\" column number \"3\" into the variable \"in" +
                    "itialKudos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.And("I click on the element using tag \"span\" attribute type \"data-kudos-amount\" attrib" +
                    "ute value \"1\" in row number \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 136
 testRunner.And("I set the text box using element id \"kudo_transaction\" with the value \"Awesome!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.And("I click on the button using class name \"give-btn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08-Logout as a Regular User")]
        public virtual void _08_LogoutAsARegularUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08-Logout as a Regular User", ((string[])(null)));
#line 140
this.ScenarioSetup(scenarioInfo);
#line 141
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 142
 testRunner.When("I click on the link containing the text \"Sign out\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
 testRunner.Then("the page contains the text \"You need to sign in or sign up before continuing\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 144
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09-Admin Login Credentials (VD-32)")]
        public virtual void _09_AdminLoginCredentialsVD_32()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09-Admin Login Credentials (VD-32)", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line 147
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 149
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.Then("the page contains the text \"Signed in successfully\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10-Manage Employees")]
        public virtual void _10_ManageEmployees()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10-Manage Employees", ((string[])(null)));
#line 154
this.ScenarioSetup(scenarioInfo);
#line 155
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 156
 testRunner.When("I click on the link containing the text \"Manage Employees\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 157
 testRunner.Then("the page contains the text \"Admin Dashboard\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11-Add New Employee")]
        public virtual void _11_AddNewEmployee()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11-Add New Employee", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line 160
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 161
 testRunner.When("I click on the link containing the text \"Add New Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 162
 testRunner.And("the page contains the text \"Add New Employee\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("I save a random string with \"8\" characters into the variable \"username\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And("I set the text box using element id \"employee_username\" with the value stored in " +
                    "the variable \"username\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"Autotest1" +
                    "23!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.And("I set the text box using element id \"employee_password_confirmation\" with the val" +
                    "ue \"Autotest123!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 173
 testRunner.And("I append the following strings \"[username],@,test.com\" and save the result into t" +
                    "he variable \"emailAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.And("I set the text box using element id \"employee_email\" with the value stored in the" +
                    " variable \"emailAddress\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 176
 testRunner.And("I set the text box using element id \"employee_first_name\" with the value \"TestUse" +
                    "r-FN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("I set the text box using element id \"employee_last_name\" with the value \"User-LN\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.And("I set the checkbox with element id \"employee_is_admin\" to \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 179
 testRunner.And("I click on the submit button labeled \"Save changes\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.Then("the page contains the text \"Employee was successfully created\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("72-VD-25 - Peer Kudos Dashboard - Employee of the Previous Month")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _72_VD_25_PeerKudosDashboard_EmployeeOfThePreviousMonth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("72-VD-25 - Peer Kudos Dashboard - Employee of the Previous Month", new string[] {
                        "ignore"});
#line 184
this.ScenarioSetup(scenarioInfo);
#line 186
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 187
 testRunner.Then("the page using element id \"Panel-Last Month\'s Winner\" and attribute type \"div\" co" +
                    "ntains the text \"Alex Duan\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("73-VD-29 - Peer Kudos Dashboard - Assign stars to employees in Top 5")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _73_VD_29_PeerKudosDashboard_AssignStarsToEmployeesInTop5()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("73-VD-29 - Peer Kudos Dashboard - Assign stars to employees in Top 5", new string[] {
                        "ignore"});
#line 191
this.ScenarioSetup(scenarioInfo);
#line 193
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 194
 testRunner.When("I save the data using element id \"top_1_of_5_employee\" into the variable \"current" +
                    "StarCount\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 195
 testRunner.And("I click on the button using element id \"3-star\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("75-VD-27 - Peer Kudos Dashboard - My Current Month Ranking")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _75_VD_27_PeerKudosDashboard_MyCurrentMonthRanking()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("75-VD-27 - Peer Kudos Dashboard - My Current Month Ranking", new string[] {
                        "ignore"});
#line 205
this.ScenarioSetup(scenarioInfo);
#line 210
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 213
 testRunner.Then("the element using element Id \"Panel-Last Month\'s Winner\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 214
 testRunner.Then("the element using element Id \"my_star_given_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 215
 testRunner.Then("the element using element Id \"my_star_remaining_count\" contains the text \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 216
 testRunner.And("I close the current page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("76-VD-32 - Admin - Login")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _76_VD_32_Admin_Login()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("76-VD-32 - Admin - Login", new string[] {
                        "ignore"});
#line 219
this.ScenarioSetup(scenarioInfo);
#line 222
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"ShoppingD" +
                    "emo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 223
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"admin@exa" +
                    "mple.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 224
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"supers" +
                    "ecret\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 226
 testRunner.Then("the page title is \"ShoppingDemo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 227
 testRunner.And("the page contains the text \"Catalog\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("77-VD-24 - Peer Kudos Dashboard - Valid Admin Login Credentials")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _77_VD_24_PeerKudosDashboard_ValidAdminLoginCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("77-VD-24 - Peer Kudos Dashboard - Valid Admin Login Credentials", new string[] {
                        "ignore"});
#line 230
this.ScenarioSetup(scenarioInfo);
#line 231
 testRunner.Given("I navigate to the url \"http://env03.cloud.capitissolutions.com\" titled \"Employee " +
                    "Kudos MVP\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 232
 testRunner.When("I set the text box using element id \"employee_username\" with the value \"alex\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 233
 testRunner.And("I set the text box using element id \"employee_password\" with the value \"alexrules" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.And("I click on the submit button labeled \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 235
 testRunner.Then("the page contains the text \"Profile\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 236
 testRunner.And("the page contains the text \"Kudos Received\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("78-VD-32 - Admin - Login with Valid Credentials")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        public virtual void _78_VD_32_Admin_LoginWithValidCredentials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("78-VD-32 - Admin - Login with Valid Credentials", new string[] {
                        "ignore"});
#line 239
this.ScenarioSetup(scenarioInfo);
#line 240
 testRunner.Given("the page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 241
 testRunner.When("I set the text box using element id \"login_email_field\" with the value \"invalidUs" +
                    "erId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 242
 testRunner.And("I set the text box using element id \"login_password_field\" with the value \"invali" +
                    "dPassword\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 243
 testRunner.And("I click on the button using element id \"login_submit_button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 244
 testRunner.Then("the page contains the text \"Invalid Email or password.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
